name: Continuous Integration

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pip install -r backend/requirements.txt

    - name: run pre-commit hooks
      run: |
        cd backend
        pre-commit run --all-files

    - name: run pytest
      run: |
        cd backend
        pytest test
