name: Continuous Integration

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort mypy flake8
        pip install -r requirements.txt

    - name: run pytest
      run: pytest backend/test

    - name: check code format with black
      run: black --check --line-length 120 --target-version py39 backend/

    - name: sort imports with isort
      run: isort --check-only --profile black backend/

    - name: run mypy
      run: mypy --ignore-missing-imports backend/

    - name: lint with flake8
      run: flake8 backend/ --max-line-length=120 --exclude=backend/migrations/
