name: Deploy to EC2

on:
  push:
    branches: [master]

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: create env file
      run: |
        touch .env.dev.docker

        echo DJANGO_ENV=${{secrets.DJANGO_ENV}} >> .env.dev.docker
        echo DJANGO_SETTINGS_MODULE=${{secrets.DJANGO_SETTINGS_MODULE}} >> .env.dev.docker

        echo SECRET_KEY=${{secrets.SECRET_KEY}} >> .env.dev.docker
        echo ALLOWED_HOSTS=${{secrets.ALLOWED_HOSTS}} >> .env.dev.docker
        echo DEBUG=${{secrets.DEBUG}} >> .env.dev.docker

        echo POSTGRES_DB=${{secrets.POSTGRES_DB}} >> .env.dev.docker
        echo POSTGRES_USER=${{secrets.POSTGRES_USER}} >> .env.dev.docker
        echo POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}} >> .env.dev.docker
        echo POSTGRES_HOST=${{secrets.POSTGRES_HOST}} >> .env.dev.docker
        echo POSTGRES_PORT=${{secrets.POSTGRES_PORT}} >> .env.dev.docker

        echo EMAIL_HOST_USER=${{secrets.EMAIL_HOST_USER}} >> .env.dev.docker
        echo EMAIL_HOST_PASSWORD=${{secrets.EMAIL_HOST_PASSWORD}} >> .env.dev.docker
        echo SERVER_EMAIL=${{secrets.SERVER_EMAIL}} >> .env.dev.docker
        echo DEFAULT_FROM_MAIL=${{secrets.DEFAULT_FROM_MAIL}} >> .env.dev.docker

        echo DJANGO_SUPERUSER_PASSWORD=${{secrets.DJANGO_SUPERUSER_PASSWORD}} >> .env.dev.docker
        echo DJANGO_SUPERUSER_EMAIL=${{secrets.DJANGO_SUPERUSER_EMAIL}} >> .env.dev.docker
        echo DJANGO_SUPERUSER_USERNAME=${{secrets.DJANGO_SUPERUSER_USERNAME}} >> .env.dev.docker

    - name: create remote directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: mkdir -p /home/ubuntu/srv

    - name: copy source via ssh key
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        remote_path: /home/ubuntu/srv/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        working-directory: /home/ubuntu/srv
        script: |
          sh ./deploy.sh
